query
    = statement EOF ;

statement
    = show_tables
    | describe_table
    | select;

show_tables
    = "SHOW" "TABLES" [";"] ;

describe_table
    = "DESCRIBE" "TABLE" identifier [";"] ;

select
    = "SELECT" projection "FROM" identifier [order] [limit] [";"] ;

projection
    = "*"
    | identifier ("," identifier)*

order
    = "ORDER" "BY" sort_key ("," sort_key)*

sort_key
    = identifier [direction]

direction
    = "ASC"
    | "DESC";

limit
    = "LIMIT" number;

number
    = NUMBER ;

identifier
    = IDENTIFIER ;

