query
    = statement EOF ;

statement
    = show_tables
    | describe_table
    | select;

show_tables
    = "SHOW" "TABLES" [";"] ;

describe_table
    = "DESCRIBE" "TABLE" identifier [";"] ;

select
    = "SELECT" projection "FROM" identifier [limit] [";"] ;

projection
    = "*"
    | identifier ("," identifier )*

limit
    = "LIMIT" number;

number
    = NUMBER ;

identifier
    = IDENTIFIER ;

